### ISSUE TITLE
valueaccounting test error

### ISSUE THREAD

**Issue by bhaugen** [LearnDeepMilwaukee/valuenetwork#5]
This is probably unfair to throw at new programmers, but here it is anyway. The source of the error is deep into the graphql code. I've fixed it in another place and it might be better to leave it to me. I'll get it later this week, unless some very brave soul gets there first.

This error occurs when doing ```./manage.py test valuenetwork.valueaccounting```:
```
======================================================================
ERROR: test_commitment_change_propagation (valuenetwork.valueaccounting.tests.test_explosions.ExplosionTest)
Propagate changes to dependants
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bob/Envs/LearnDeep/valuenetwork/valuenetwork/valueaccounting/tests/test_explosions.py", line 278, in test_commitment_change_propagation
    self.order)
  File "/home/bob/Envs/LearnDeep/valuenetwork/valuenetwork/valueaccounting/views.py", line 9027, in handle_commitment_changes
    ex_ct.delete_dependants()
  File "/home/bob/Envs/LearnDeep/valuenetwork/valuenetwork/valueaccounting/models.py", line 9672, in delete_dependants
    proc.delete()
  File "/home/bob/Envs/LearnDeep/local/lib/python2.7/site-packages/django/db/models/base.py", line 973, in delete
    return collector.delete()
  File "/home/bob/Envs/LearnDeep/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 284, in delete
    count = qs._raw_delete(using=self.using)
  File "/home/bob/Envs/LearnDeep/local/lib/python2.7/site-packages/django/db/models/query.py", line 631, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/home/bob/Envs/LearnDeep/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 80, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/bob/Envs/LearnDeep/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
OperationalError: no such table: api_fulfillment
```

**Comment by bhaugen** [comment]
I'm closing this one because I had already fixed it in this commit in the upstream api-extensions branch:
https://github.com/FreedomCoop/valuenetwork/commit/1f085b1f73c22af62298baabe9a55d0fbf709947

**Comment by bhaugen** [comment]
A little explanation might be good, anyway: this is an example of how Django's ORM (Object-Relational Manager) works:
* Fulfillment is a class in the api app that has ForeignKeys to two different models in the valueaccounting app, including EconomicEvent.
* When you delete an EconomicEvent object, the ORM looks at all the ForeignKey relationships and does whatever you told it to do on_delete in those relationships. The default is on_delete=CASCADE, which means, delete the related record, too. 
* But the Fulfillment class is set to managed = False, which means the ORM does not manage it, and so can't delete its instances. Which caused that error when a test tried to delete an EconomicEvent.
* So the fix was to set those ForeignKeys to on_delete=DO_NOTHING. Now the ORM is happy, because it can do that. And the tests pass again.
